spring:
  application:
    name: chat-sample
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/,classpath:/static/

server:
  port: 8080

# 灵积平台 api 适用于新版 sdk
dash:
  llm:
    appId:
    apikey:
    model: qwen-max
    topK: 1
    seed: 1234
  voice:
    model: cosyvoice-v1
    voice: longxiaochun

# 百炼平台 api 适用于旧版 sdk
chat:
  llm:
    #[需修改]阿里云accessKeyId, 参考文档https://help.aliyun.com/document_detail/2587494.html?spm=a2c4g.2587492.0.0.2fe9630b3xtcS8
    accessKeyId:
    #[需修改]阿里云accessKeySecret
    accessKeySecret:
    #[需修改]百炼AgentKey
    agentKey:
    #[需修改]百炼应用id, 配置多个对话应用时，需要跟page_config.json中的chatTabs里的code一一对应, 也就是一个tab的code对应一个百炼appId
    appIds:
      text_chat:
      doc_chat:
      table_chat:
    # POP网关地址
    popEndpoint:
    # 百炼网关地址
    endpoint:
    timeout: 60 #llm请求超时时间60秒
    #[需修改]一句话语音识别 key
    nlsKey:
    topK: 1
    seed: 1234
  doc:
    #[需修改]向量数据库id
    storeId:
    #[需修改]文件数据库id
    fileStoreId:
    timeout: 60 #文档导入超时时间
  security:
    refererWhitelist:
      - http://127.0.0.1:8080
      - https://ai.forsize.cn/
      - https://121.43.108.153/
  app:
    openTrace: true
    sessionMaxMessages: 50 #对话记录, 最多50条
    sessionTtl: 2 #对话缓存时间, 2小时

  cache:
    type: caffeine #缓存配置, redis|caffeine, 默认为caffeine

#redis:
#  host: 127.0.0.1
#  port: 6379
#  password:
aliyun:
  appKey:
  url: wss://nls-gateway-cn-beijing.aliyuncs.com/ws/v1

# cosyvoice 智能语音平台（非 dash）
TTSFlowing:
  speechVoice:
  speechVolume: 50
  speechPitchRate: 0
  speechRate: 0
  minSendIntervalMS: 100
  uploadAudioDir: ./uploadAudio

pdc:
  tts: http://121.199.64.87:8000

xmly:
  authToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NDEyNTc0ODcsImlhdCI6MTcyNTcwNTQ4Nywic3ViIjoiYmFvc2hpamllIn0.PdeRyDc5lAS_3WziGRbem7mS5lyhDU3js5zZmOqkKhk
  rate: 55.0
  volume: 50.0
  pitch: 60.0
  domain: 播客
  speakerName: 保时捷音色克隆测试V1Pro
  speakerVariant: 自然聊天
